name: main
on:
  # push trigger required to get coveralls monitoring of default branch
  # pull_request required to get PR coveralls comments
  push:
    branches: [main]
  pull_request:
    branches: [main]

# no need to bother caching bun deps
# https://github.com/oven-sh/setup-bun/issues/14#issuecomment-1714116221
jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      any_ts_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            {src,test}/**/*.ts
            package.json
            tsconfig.json

  _test:
    needs: changed-files
    if: needs.changed-files.outputs.any_ts_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun test --coverage --coverage-reporter lcov --coverage-dir .
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.0
        with:
          format: lcov
          file: lcov.info

  test:
    needs: _test
    # workaround for https://github.com/orgs/community/discussions/13690
    # https://stackoverflow.com/a/77066140/9771158
    if: ${{ !(failure() || cancelled()) }}
    runs-on: ubuntu-latest
    steps:
      - name: Tests OK (passed or skipped)
        run: true

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Validate
        run: |
          bun concurrently \
            -c auto \
            -n format,lint,typecheck \
            'bun dprint check' \
            'bun biome check --config-path=.biome.jsonc .' \
            'bun tsc'
