name: main
on:
  # push trigger required to get coveralls monitoring of default branch
  # pull_request required to get PR coveralls comments
  push:
    branches: [main]
  pull_request:
    branches: [main]

# no need to bother caching bun deps
# https://github.com/oven-sh/setup-bun/issues/14#issuecomment-1714116221
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Validate
        run: |
          bun concurrently \
            -c auto \
            -n format,lint,typecheck-server,typecheck-client \
            'bun dprint check' \
            'bun biome check --config-path=.biome.jsonc .' \
            'bun tsc --noEmit --project server/tsconfig.json' \
            'bun tsc --noEmit --project client/tsconfig.json'
